
def clean_gtp_response(body):
    """ Convert GPT response into realistic tweet text
    """
    msg = None
    tweet = body[0].text

    # Clean up space generated by text completion
    if "\n\n" in tweet:
      tweet = tweet.split("\n\n")[1]

    # remove double hashtag
    tweet = tweet.replace("##", "#")
    
    # Sometime GPT puts its response in a quote
    tweet = tweet.replace("\"", "")

    # do not tweet with these strngs
    invalid_strings = ["2020", "COVID", "pandemic"]
    for string in invalid_strings:
        if string in tweet:
            msg = f"InvalidStringError: {string}"

    # max tweet length == 280
    tweet_len = len(tweet)
    if tweet_len > 280:
        msg = f"InvalidLengthError: {tweet_len}"

    # invalid tweets will contain msg attribute
    if msg:
        return {"msg": msg, "tweet": tweet}
    else:
        return {"tweet": tweet}

